# Imported settings - migrated from TSLint
env:
  node: true
extends:
  - eslint:recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "@typescript-eslint/tslint"
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-console:
    - off
  "@typescript-eslint/indent":
    - warn
    - 4
    - FunctionDeclaration:
        parameters: first
      FunctionExpression:
        parameters: first
  "@typescript-eslint/semi":
    - error
    - never
  "@typescript-eslint/quotes":
    - error
    - single
