root: true
parser: "@typescript-eslint/parser"
env:
    node: true
plugins:
    - "@typescript-eslint"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
rules:
    indent:
        - warn
        - tab
    semi:
        - warn
        - never
    quotes:
        - warn
        - single
    no-unused-vars:
        - warn
        - vars: local
          args: none
    "@typescript-eslint/no-unused-vars":
        - warn
        - vars: local
          args: none
    no-use-before-define:
        - off
    "@typescript-eslint/no-use-before-define":
        - off
    "@typescript-eslint/no-explicit-any":
        - off
