# THIS FILE CONTAINS ALL AVAILABLE CONFIG SETTINGS.
# PLEASE USE DEFAULT.RECOMMENDED.YML AS A TEMPLATE!
#              THANK YOU!                 - hadenpf

discord:
  token: DISCORD_BOT_TOKEN
nlp:
  enable: false
  wit_token: WIT_SERVER_TOKEN
  ignore_prefix: \# # NLP will ignore messages starting with this
  restrict: true # Restrict NLP to test_channel only?
  test_channel: NLP_TEST_CHANNEL_ID # Bot will print results to user
  results_channel: NLP_LOG_CHANNEL_ID
commands:
  default_prefix: "!"
moderation:
  logs:
    channel: MOD_LOG_CHANNEL_ID
    reason_time: 60 # Amount of time to wait for a response if no reason was provided on a ban, in seconds.
    events:
      ban: true
      kick: true
  auto_unban: # FOR DEBUGGING ONLY! DO NOT USE IN PRODUCTION!
    enable: true
    user_id:
      - UNBAN_USER_ID
    guild_id: UNBAN_GUILD_ID
logging:
  file: false # Disables console logging if set true
database:
  client: mysql2
  connection:
    host: DB_HOST
    user: DB_USER
    password: DB_PASS
    database: DB_NAME
other:
  log_guilds: # Log guilds/guild count on startup?
    enable: true
    list: false
