discord:
  token: DISCORD_BOT_TOKEN
nlp:
  enable: false
  wit_token: WIT_SERVER_TOKEN
  ignore_prefix: \# # NLP will ignore messages starting with this
  restrict: true # Restrict NLP to test_channel only?
  test_channel: NLP_TEST_CHANNEL_ID # Bot will print results to user
  results_channel: NLP_LOG_CHANNEL_ID
commands:
  default_prefix: "!"
moderation:
  logs:
    channel: MOD_LOG_CHANNEL_ID
    reason_time: 60 # Amount of time to wait for a response if no reason was provided on a ban, in seconds.
    events:
      ban: true
      kick: true
  auto_unban: # FOR DEBUGGING ONLY! DO NOT USE IN PRODUCTION!
    enable: true
    user_id:
      - "342450626921496589"
    guild_id: "516764994965340161"
logging:
  file: false # Disables console logging if set true
