discord:
  token: TOKEN_HERE
nlp:
  enable: false
  wit_token: TOKEN_HERE
  # results_channel: NLP_LOG_CHANNEL_ID # Master NLP logs channel
  # test_channel: NLP_TEST_CHANNEL_ID # DEBUGGING: Print NLP results in this channel
  # restrict: true # Only analyze with NLP in test_channel
commands:
  default_prefix: "!"
moderation:
  logs:
    channel: MODERATION_LOG_CHANNEL_ID
    events:
      ban: true
      kick: true
utils:
  owner_id: BOT_OWNER_ID_HERE
logging:
  file: true # Disables console logging if true. Recommended = true.
