discord:
  token: TOKEN_HERE
nlp:
  enable: false
  wit_token: TOKEN_HERE
  ignore_prefix: \#
  restrict: false # Restrict NLP to test_channel only?
  test_channel: null
  results_channel: null
commands:
  default_prefix: "-"
utils:
  owner_id: "377638029008830466"
logging:
  file: true # Disables console logging if set true
